# Generated by Django 3.0 on 2019-12-29 13:01

import brands.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=brands.models.NameField(max_length=200),
        ),
    ]
