# Generated by Django 3.0 on 2019-12-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('on_sale_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='NEW', max_length=4)),
                ('ram', models.IntegerField(default=1)),
                ('memory', models.IntegerField(default=1)),
                ('camera', models.IntegerField(default=1)),
                ('screen_dimension', models.FloatField(default=1)),
                ('screen', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.Brand')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('material', models.CharField(max_length=200)),
                ('phone', models.ManyToManyField(to='product.Phone')),
            ],
            bases=('product.product',),
        ),
    ]
