# Generated by Django 3.0 on 2019-12-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191212_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
