# Generated by Django 3.0 on 2019-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191212_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
