# Generated by Django 3.0 on 2019-12-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191212_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory')], default='phone', max_length=10),
        ),
    ]
