# Generated by Django 3.0 on 2019-12-29 13:09

import brands.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191229_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='material',
            field=brands.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen',
            field=brands.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=brands.models.NameField(max_length=200),
        ),
    ]
